spring:
    datasource:
      url: jdbc:mysql://localhost:3306/springboot_blog
      username: root
      password: root
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
      #关闭thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为true。
       cache: false
       mode: LEGACYHTML5

    mvc:
      static-path-pattern: /**
      view:
        prefix: /
        suffix: .html

debug: true

shiro:
    home:
      pre:
      url:
      logout:
    success:
      url: /home
    login:
      url: /login